<?php
/**
 * Os Studios PagSeguro Api Payment Module
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   OsStudios
 * @package    OsStudios_PagSeguroApi
 * @copyright  Copyright (c) 2013 Os Studios (www.osstudios.com.br)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Tiago Sampaio <tiago.sampaio@osstudios.com.br>
 */
?>

<p>
    <strong><?php echo $this->getMethod()->getTitle() ?></strong>
    
    <?php if ($this->getShowPaylink()): ?>
    	(<a href="<?php echo $this->getPayUrl(); ?>" onclick="this.target='_blank'">pagar</a>)
    <?php endif; ?>

    <?php if ($this->getShowInfo()): ?>
    	<br/>
        <br/><?php echo $this->__('<b>Transaction ID</b>: %s', $this->getInfo()->getPagseguroInfo()->getPagseguroTransactionId())?>
        <br/><?php echo $this->__('<b>Transaction Date</b>: %s', Mage::getModel('core/date')->date('d/m/Y H:i:s', $this->getInfo()->getPagseguroInfo()->getPagseguroTransactionDate()))?>
        <br/><?php echo $this->__('<b>Payment Method</b>: %s', $this->getInfo()->getPagseguroInfo()->getPaymentMethod())?>
        <br/>
    <?php endif; ?>
</p>